version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7.30
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: naresh
          MYSQL_PASSWORD: abcdefgh

    steps:
      - checkout
      - run:
          name: Build JAR
          command: |
            mvn clean package
      - run:
          name: Waiting for MYSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc  -z  127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MYSQL && exit 1
      
      - run:
          name: Running test
          command: |
            mvn test

  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7.30
        environment:
          MYSQL_ROOT_PASSWORD:  password
          MYSQL_DATABASE: test
          MYSQL_USER: naresh
          MYSQL_PASSWORD: abcdefgh

    steps:
      - checkout
      - run:
          name: Build JAR
          command: |
            mvn clean package
      - run:
          name: Waiting for MYSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc  -z  127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MYSQL && exit 1
      
      - run:
          name: Running test
          command: |
            mvn test

workflows:
  version: 2
  pr-check:
    jobs:
      - pr_check

  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master